/**
 * seed-sinapi-composicoes.ts
 *
 * Seeds SINAPI Composicoes from a pre-extracted CSV (generated by extract-composicoes.ps1)
 * into the `sinapi_itens` Firestore collection.
 *
 * Workflow:
 *   1. Run: powershell -ExecutionPolicy Bypass -File scripts/extract-composicoes.ps1
 *   2. Run: npx tsx scripts/seed-sinapi-composicoes.ts [MES_ANO] [UF] [SKIP]
 *
 * Usage:
 *   npx tsx scripts/seed-sinapi-composicoes.ts 08/2026 PR
 *   npx tsx scripts/seed-sinapi-composicoes.ts 08/2026 PR 9600   # resume from row 9600
 */

import { initializeApp, cert } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import * as dotenv from 'dotenv'
import * as path from 'path'
import * as fs from 'fs'
import * as readline from 'readline'

dotenv.config({ path: path.resolve(process.cwd(), '.env') })

// ── Firebase init ──────────────────────────────────────────────────────────
try {
  const serviceAccountRaw = process.env.FIREBASE_SERVICE_ACCOUNT_KEY
  let serviceAccount: any
  if (serviceAccountRaw) {
    serviceAccount = JSON.parse(serviceAccountRaw)
    if (serviceAccount.private_key) {
      serviceAccount.private_key = serviceAccount.private_key.replace(/\\n/g, '\n')
    }
  }
  if (serviceAccount) {
    initializeApp({ credential: cert(serviceAccount) })
  } else {
    initializeApp()
  }
} catch (error) {
  console.error('Firebase init error:', error)
  process.exit(1)
}

const db = getFirestore()
const FIRESTORE_BATCH_SIZE = 400
const COLLECTION = 'sinapi_itens'
const CSV_PATH = path.resolve('scripts/composicoes_temp.csv')

// Parse a CSV line respecting quoted fields
function parseCsvLine(line: string): string[] {
  const result: string[] = []
  let current = ''
  let inQuotes = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]
    if (c === '"') {
      if (inQuotes && line[i + 1] === '"') { current += '"'; i++ }
      else { inQuotes = !inQuotes }
    } else if (c === ',' && !inQuotes) {
      result.push(current); current = ''
    } else {
      current += c
    }
  }
  result.push(current)
  return result
}

async function main() {
  const [,, mesAnoArg = '08/2026', ufArg = 'PR', skipArg = '0'] = process.argv
  const mesAno = mesAnoArg
  const uf = ufArg.toUpperCase()
  const skip = parseInt(skipArg) || 0

  if (!fs.existsSync(CSV_PATH)) {
    console.error(`CSV not found: ${CSV_PATH}`)
    console.error('Run first: powershell -ExecutionPolicy Bypass -File scripts/extract-composicoes.ps1')
    process.exit(1)
  }

  console.log(`\nSeeding from: ${CSV_PATH}`)
  console.log(`UF: ${uf} | Mes/Ano: ${mesAno} | Skipping first: ${skip} rows`)

  // Read entire CSV at once (it's ~1.7MB — very manageable)
  let csvContent = fs.readFileSync(CSV_PATH, 'utf8')
  // Strip UTF-8 BOM if present
  if (csvContent.charCodeAt(0) === 0xFEFF) csvContent = csvContent.slice(1)

  const lines = csvContent.split('\n').filter(l => l.trim())
  console.log(`Total CSV lines (incl. header): ${lines.length}`)

  let inserted = 0
  let skipped = 0
  let dataRow = 0
  let batchItems: any[] = []

  const flush = async () => {
    if (!batchItems.length) return
    const batchOps = db.batch()
    batchItems.forEach(item => {
      const docRef = db.collection(COLLECTION).doc(`comp_${item.codigo}`)
      batchOps.set(docRef, item, { merge: true })
    })
    await batchOps.commit()
    inserted += batchItems.length
    console.log(`  Wrote ${batchItems.length} (total: ${inserted})`)
    batchItems = []
  }

  for (let i = 1; i < lines.length; i++) {  // start at 1 to skip header
    dataRow++
    if (dataRow <= skip) continue

    const [codigo, descricao, unidade, precoStr] = parseCsvLine(lines[i])
    const preco = parseFloat(precoStr) || 0

    if (!codigo || !descricao) { skipped++; continue }

    batchItems.push({
      codigo,
      descricao,
      unidade,
      custo_desonerado: preco,
      custo_nao_desonerado: preco,
      uf,
      mes_ano: mesAno,
      tipo: 'composicao',
    })

    if (batchItems.length >= FIRESTORE_BATCH_SIZE) {
      await flush()
    }
  }

  await flush()

  console.log(`\n✅ Done! Inserted: ${inserted}, Skipped: ${skipped}`)
  console.log(`   Collection: ${COLLECTION} | UF: ${uf} | Mes/Ano: ${mesAno}\n`)
}

main().catch(err => {
  console.error('Fatal error:', err)
  process.exit(1)
})
